config/routes.rb
Rails.application.routes.draw do

  root to: 'posts#top'
  get '/about' => 'static_pages#about'
  get 'posts/admin' => 'posts#admin'
  get 'top' => 'posts#top'

  devise_for :users
  resources :genres,         only: [:create, :index, :update, :destroy]
  resources :emotions,       only: [:create, :index, :update, :destroy]
  resources :contacts,       only: [:new, :create, :show, :index, :update, :destroy]
  resources :relationships,  only: [:create, :destroy]

  resources :users do
    member do
      get :following, :followers
      get :delete
      get :report
      get :timeline
    end
  end

  resources :posts,      only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :postimages
    resource :favorites, only: [:create, :destroy]
    resources :comments,  only: [:create, :destroy]
  end
end

app/models/emotion.rb
class Emotion < ApplicationRecord
	has_many :posts

	validates :emotion_name, presence: true,
							 length: { maximum: 10 },
							 uniqueness: true #値がユニークか検証する
end

app/controllers/emotions_controller.rb
class EmotionsController < ApplicationController
  before_action :admin_user

  def create
    @emotion = Emotion.new(emotion_params)
    if @emotion.save
      flash[:notice] = '登録しました。'
      redirect_to emotions_path
    else
      @emotions = Emotion.page(params[:page]).per(10).reverse_order
      flash[:notice] = '同名以外の１０文字以内で登録可能です。'
      render :index
    end
  end

  def index
    @emotion = Emotion.new
    @emotions = Emotion.page(params[:page]).per(10).reverse_order
  end

  def update
    @emotion = Emotion.find(params[:id])
    if @emotion.update(emotion_params)
      flash[:notice] = '更新しました。'
      redirect_to emotions_path
    else
      @emotions = Emotion.page(params[:page]).per(10).reverse_order
      flash[:notice] = '同名以外の１０文字以内で登録可能です。'
      render :index
    end
  end

  def destroy
    @emotion = Emotion.find(params[:id])
    posts = Post.where(emotion_id: @emotion)
    if posts.blank?
      @emotion.destroy
      flash[:notice] = '削除しました。'
      redirect_to emotions_path
    else
      @emotions = Emotion.page(params[:page]).per(10).reverse_order
      flash[:notice] = 'この気分で投稿されている記事があります。'
      render :index
    end
  end


  private

  def emotion_params
    params.require(:emotion).permit(:emotion_name)
  end
end

app/helpers/emotions_helper.rb
module EmotionsHelper
end

app/views/emotions/index.html.erb
<section class="container">
  <div class="row">
    <div class="col-xs-4 col-sm-7 col-lg-9">
      <h1 class="emotion_title_list">気分一覧</h1>
    </div>
    <div class="col-xs-8 col-sm-5 col-lg-3">
      <%= form_for(@emotion) do |f| %>
        <div class="input-group emotion_new">
          <%= f.text_field :emotion_name, required: true, class: 'form-control' %>
          <span class="input-group-btn">
            <%= f.submit "新規登録", class: 'btn btn-default' %>
          </span>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>ID</th>
          <th>気分名</th>
          <th>編集</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @emotions.each do |emotion| %>
          <%= form_for(emotion) do |f| %>
            <tr class="admin_emotion">
              <td><%= emotion.id %></td>
              <td><%= emotion.emotion_name %></td>
              <td><%=  f.text_field :emotion_name, class: 'form_control' %></td>
              <td><%= f.submit "更新", class: 'btn btn-default' %></td>
              <td><%= link_to '削除', emotion_path(emotion.id), method: :delete, "data-confirm" => "削除しますか？", class: 'btn btn-link' %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <%= paginate @emotions %>
  </div>
</section>