config/routes.rb
Rails.application.routes.draw do

  root to: 'posts#top'
  get '/about' => 'static_pages#about'
  get 'posts/admin' => 'posts#admin'
  get 'top' => 'posts#top'

  devise_for :users
  resources :genres,         only: [:create, :index, :update, :destroy]
  resources :emotions,       only: [:create, :index, :update, :destroy]
  resources :contacts,       only: [:new, :create, :show, :index, :update, :destroy]
  resources :relationships,  only: [:create, :destroy]

  resources :users do
    member do
      get :following, :followers
      get :delete
      get :report
      get :timeline
    end
  end

  resources :posts,      only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :postimages
    resource :favorites, only: [:create, :destroy]
    resources :comments,  only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
# フォローする側(active_relationships)擬似的に作成。foreign_keyでされる側id指定している
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
#フォローしているユーザーを取り出す
  has_many :following, through: :active_relationships
# フォローされてるユーザーを取り出せる(user.followers)
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :followers, through: :passive_relationships

  attachment :profile_image
  attachment :profile_headerimage

  validates :name, presence: true, length: { minimum: 2, maximum: 15 }
  validates :introduction, length: { maximum: 150 }
  validates :email, presence: true, length: { maximum: 80 }


# フォロー関連
  def follow(other_user)
    active_relationships.create(following_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(following_id: other_user.id).destroy
  end
	# フォローしているかどうか(t or f)
  def following?(other_user)
    following.include?(other_user)
  end

# 検索関連
  def self.search(search)#selfはUser
    if search
      where(['name LIKE ?', "%#{search}%"])#検索内とnameの部分一致を表示
    else# SQL記述 %は0字以上の任意文字列
      all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :admin_user, only: [:index]

  def show
    @user = User.find(params[:id])
    @genres_data = Post.joins(:genre).where(user_id: params[:id]).order(impressions_count: 'DESC').limit(4)
    @emotions_data = Post.joins(:emotion).where(user_id: params[:id]).order(impressions_count: 'DESC').limit(4)
    @new_posts = Post.page(params[:page]).where(user_id: params[:id]).per(12).reverse_order
    @post_pv_counts = Post.where(user_id: params[:id]).group(:impressions_count).order(impressions_count: "DESC").limit(5)
  #いいね数多い記事取得
    post_favorite_count = Post.joins(:favorites).where(user_id: params[:id]).group(:post_id).count
    post_favorited_ids = Hash[post_favorite_count.sort_by{ |_, v| -v }].keys
    @popular_posts = Post.where(id: post_favorited_ids).limit(4)
  end

  def index
    @users = if params[:search]
      User.page(params[:page]).per(10).where('name LIKE ?', "%#{params[:search]}%").reverse_order
    else
      User.page(params[:page]).per(10).reverse_order
    end
  end

  def edit
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(20).reverse_order
    unless @user.id == current_user.id
      redirect_to root_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = '更新しました。'
      redirect_to user_path
    else
      @posts = @user.posts.page(params[:page]).per(20).reverse_order
      flash[:notice] = 'ユーザーネーム１５文字以内、紹介文１５０文字以内です。'
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    if current_user.admin?
      redirect_to users_path
    else
      flash[:notice] = '退会しました。ご利用ありがとうございました。'
      redirect_to root_path
    end
  end

  def delete
    @user = User.find(params[:id])
    if @user.id == current_user.id
    elsif current_user.admin?
    else
      redirect_to root_path
    end
  end

  def timeline
    @user = User.find(params[:id])
    @users = @user.following.all
    @timeline = Post.page(params[:page]).where(user_id: @users).per(10).order(created_at: :DESC)
    unless @user.id == current_user.id
      redirect_to root_path
    end
  end

  def report
    user = User.find(params[:id])
    @total_pv = Post.where(user_id: user).sum(:impressions_count)
    pv_counts = Post.where(user_id: user, created_at: 1.weeks.ago..Date.today).group('date(created_at)').sum(:impressions_count)
    @pv_counts = if pv_counts.empty?
      {Date.today => 0}
    else
      pv_counts
    end
    @genres_data = Post.joins(:genre).where(user_id: user).order(impressions_count: 'DESC').limit(10)
    @emotions_data = Post.joins(:emotion).where(user_id: user).order(impressions_count: 'DESC').limit(10)
    unless user.id == current_user.id
      redirect_to root_path
    end
  end

  def following
    @user = User.find(params[:id])
    @users = @user.following.page(params[:page]).per(20).reverse_order
    render 'show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers.page(params[:page]).per(20).reverse_order
    render 'show_follower'
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :profile_headerimage, :profile_image, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_side.html.erb
<%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: '/images/no_image.jpg', class: 'profile-img' %>
<br>
<p><%= user.name %></p>
<p class="text-left sidebar_introduction"><%= user.introduction%></p>
<div class="text-center">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6 follow">
        <%= link_to "フォロー #{user.following.count}", following_user_path(user) %>
      </div>
      <div class="col-md-6 follower">
        <%= link_to "フォロワー #{user.followers.count}", followers_user_path(user) %>
      </div>
    </div>
    <% if user_signed_in? %>
      <% if current_user != user %>
        <% if current_user.following?(user) %>
          <%= form_for(current_user.active_relationships.find_by(following_id: user.id), html: { method: :delete }) do |f| %>
            <%= f.submit "フォロー解除", class: 'btn btn-default btn-xs' %>
          <% end %>
        <% else %>
          <%= form_for(current_user.active_relationships.build) do |f| %>
            <%= hidden_field_tag :following_id, user.id %>
            <%= f.submit "フォロー", class: 'btn btn-default btn-xs' %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/admin.html.erb
<div class="container">
  <div class="row">
    <section class="">
      <h2>ユーザー一覧</h2>
      <%= form_tag(users_path, :method => 'get' ) do %><%# 指定しないとpost %>
        <%= text_field_tag :search %>
        <%= submit_tag "検索", :name => nil %><%#urlを消してる%>
      <% end %>
      <% @users.each do |user| %>
        <%if @users.count == 0 %>
        <% else %>
          <table class="">
            <thead>
              <tr class="info">
                <th>ID</th>
                <th>ユーザーネーム</th>
                <th>紹介文</th>
                <th>メール</th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <tr class="active">
                <td><%= user.id %></td>
                <td><%= user.name %></td>
                <td><%= user.introduction %></td>
                <td><%= user.email %></td>
                <td><%= link_to "詳細", user_path(user.id) %></td>
                <td><%= link_to "削除", user_path(user.id), method: :delete, "data-confirm" => "削除しますか？", class: 'btn-sm' %></td>
              </tr>
            </tbody>
          </table>
        <% end %>
      <% end %>
      <%= paginate @users %>
    </section>
  </div>
</div>

app/views/users/delete.html.erb
<div class ="container">
  <div class="row">
    <section class="col-xs-10 col-xs-offset-1">
      <h1 class="page-header">退会する</h1>
      <p>
        退会処理を行うと、全てのデータが削除されます。<strong>この処理は取り消しできません。</strong>
      </p>
      <p>ユーザー名：<%= @user.name %></p>
      <div class="text-right">
        <%= link_to "退会", user_path(@user.id), class: 'btn btn-danger', method: :delete, "data-confirm" => "本当に退会しますか？" %>
      </div>
    </section>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <section class="col-md-8 col-lg-9">
      <% if @posts.count == 0 %>
        <h2>まだ記事はありません。</h2>
      <% else %>
        <h2>記事管理</h2>
    <!-- 自身の記事一覧 -->
        <%= render 'posts/list', posts: @posts %>
      <% end %>
    </section>
    <!-- サイドバー ユーザー編集 -->
    <section class="col-xs-8 col-xs-offset-2 col-md-4 col-md-offset-0 col-lg-3 text-center edit_sidebar">
      <%= form_for(@user) do |f| %>
        <div class="row">
          <div class="col-xs-6 col-xs-offset-3 col-md-10 col-md-offset-1">
            <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: '/images/no_image.jpg' %>
          </div>
        </div>
        <br>
        <p>プロフィール画像</p>
        <%= f.attachment_field :profile_image %>
        <br>
        <P>マイページヘッダー画像</P>
        <%= f.attachment_field :profile_headerimage %>
        <br>
        <p>ユーザーネーム</p>
        <%= f.text_field :name, autofocus: true %><br>
        <br>
        <p>紹介文</p>
        <%= f.text_area :introduction, size: '30x10', placeholder: "自己紹介欄 150文字まで" %>
        <br>
        <p>メール</p>
        <%= f.text_field :email %>
        <br>
        <br>
        <%= f.submit "更新する", class: 'btn btn-default' %>
      <% end %>
      <div class="delete_user">
        <%= link_to "退会はこちら", delete_user_path(@user) %>
      </div>
    </section>
  </div>
</div>

app/views/users/index.html.erb
<section class="container">
  <div class="row">
    <div class="col-xs-6 col-sm-4">
      <%= link_to users_path, :style=> 'text-decoration: none;' do %>
        <h1 class="user_list_title" style="color: black;">ユーザー一覧</h1>
      <% end %>
    </div>
  <!-- 検索フォーム -->
    <div class="col-xs-6 col-sm-5">
      <%= form_tag(users_path, :method => 'get' ) do %><%# 指定しないとpost,tagはDB変更しないとき%>
        <div class="input-group user_search">
          <%= text_field_tag :search, params[:search], class: 'form-control' %>
          <span class="input-group-btn">
            <%= submit_tag "検索", class: 'btn btn-default', :name => nil %><%#urlを消してる%>
          </span>
        </div>
      <% end %>
    </div>
    <% if @users.count == 0 %>
    <% else %>
      <table class="table table-striped table-hover user">
        <thead>
          <tr class="user_list">
            <th width="5%">ID</th>
            <th class="col-xs-1">ユーザー名</th>
            <th class="col-xs-2">紹介文</th>
            <th class="col-xs-1">メール</th>
            <th class="col-xs-1"></th>
            <th class="col-xs-1"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr class="user_list">
              <td><%= user.id %></td>
              <td><%= user.name %></td>
              <td><%= user.introduction %></td>
              <td><%= user.email %></td>
              <td class="text-center"><%= link_to "詳細", user_path(user.id), class: 'btn btn-link' %></td>
              <td class="text-center"><%= link_to "削除", delete_user_path(user), class: 'btn btn-link' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @users %>
    <% end %>
  </div>
</section>

app/views/users/report.html.erb
<div class="container-fluid">
  <section>
    <h3 class="page-header">アクセス数</h3>
    <p>合計:<%= @total_pv %></p>
    <%= line_chart @pv_counts %>
  </section>
  <br>
  <section>
    <h3 class="page-header">投稿傾向</h3>
    <div class="row">
      <div class="col-sm-6">
        <%= pie_chart @genres_data.group(:genre_name).count %>
      </div>
      <div class="col-sm-6">
        <%= pie_chart @emotions_data.group(:emotion_name).count %>
      </div>
    </div>
  </section>
</div>

app/views/users/show.html.erb
<% if @new_posts.count == 0 %>
  <div class="container-fluid">
    <section class="row">
      <div class="col-xs-7 col-xs-offset-1">
        <h2>まだ記事はありません。</h2>
      </div>
      <div class="col-xs-3 text-center side">
        <%= render 'users/side', user: @user %>
      </div>
    </section>
  </div>
<% else %>
  <div class="container-fluid top">
    <div class="top_contents">
      <% @post_pv_counts.each do |post| %>
        <div class="item">
          <%= attachment_image_tag post, :post_headerimage, format: 'jpeg', fallback: '/images/no_image.jpg' %>
          <%= link_to post_path(post.id), :style=> 'text-decoration: none;' do %>
            <h4 style="color: black;"><%= post.title.truncate(20) %></h4>
          <% end %>
          <p><%= post.genre.genre_name %></p>
          <p class="text-right top_posted_date">
            投稿日:<%= post.created_at.strftime("%Y-%m-%d") %><br>
            最終更新日:<%= post.updated_at.strftime("%Y-%m-%d") %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
  <div class="container">
    <div class="row">
    <!-- 新着 -->
      <section class="col-xs-8 post_contents">
        <h2 class="page-header text-center">新着記事</h2>
        <div class="row row-eq-height">
          <% @new_posts.each do |post| %>
          <div class="col-xs-6 post_content">
            <div class="row">
              <div class="col-xs-8 col-xs-offset-2 col-sm-offset-0 col-sm-4 col-md-5 user_post_image">
                <%= attachment_image_tag post, :post_headerimage, format: 'jpeg', fallback: '/images/no_image.jpg' %>
              </div>
              <div class="col-xs-12 col-sm-8 col-md-7">
                <h4 class="user_post_title"><%= post.title.truncate(20) %></h4>
                <p class="user_post_genre"><%= post.genre.genre_name %></p>
                <p class="text-right posted_date">
                投稿日:<%= post.created_at.strftime("%Y-%m-%d") %>
                </p>
                <div class="text-center panel panel-default">
                  <%= link_to "記事を読む", post_path(post.id), :style=> 'text-decoration: none;' %>
                </div>
              </div>
            </div>
          </div>
          <% end %>
        </div>
        <%= paginate @new_posts %>
      </section>
    <!-- サイドバー -->
      <section class="col-xs-3 col-sm-offset-1 text-center sidebar">
        <div class="sidebar_top">
          <h4 class="page-header popular_headertitle">人気記事ランキング</h4>
          <% @popular_posts.each do |post| %>
            <div class="row popular_post">
              <div class="col-xs-5 user_popular_image">
                <%= attachment_image_tag post, :post_headerimage, format: 'jpeg', fallback: '/images/no_image.jpg', class: 'popular_headerimage' %>
              </div>
              <%= link_to post_path(post.id), :style=> 'text-decoration: none;' do %>
                <p class="text-left user_popularpost_title" style="color: black;"><%= post.title.truncate(20) %></p>
                <p class="text-left user_popularpost_genre" style="color: black;"><%= post.genre.genre_name %></p>
              <% end %>
            </div>
          <% end %>
        </div>
        <div class="sidebar_bottom">
        <!-- プロフィール -->
          <%= render 'users/side', user: @user %>
        <!-- 円グラフ -->
          <div class="pie_chart">
            <div class="pie_chart_top">
              <%= pie_chart @genres_data.group(:genre_name).count %>
            </div>
            <div class="pie_chart_bottom">
              <%= pie_chart @emotions_data.group(:emotion_name).count %>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
<% end %>

app/views/users/show_follow.html.erb
<div class="container">
  <section class="row">
    <h3 class="follow_title"><%= @user.name %>さんのフォロー</h3>
      <table class="table follow_lists">
        <% @users.each do |user| %>
          <tr>
            <td class="follow_user_image">
              <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: '/images/no_image.jpg' %>
            </td>
            <td class="follow_user_name">
              <%= link_to user_path(user.id), :style=> 'text-decoration: none;' do %>
                <p style="color: black;"><%= user.name %></p>
              <% end %>
            </td>
            <td class="follow_user_introduction">
              <%= user.introduction %>
            </td>
          </tr>
        <% end %>
      </table>
    <%= paginate @users %>
  </section>
</div>

app/views/users/show_follower.html.erb
<div class="container">
  <section class="row">
    <h3 class="follower_title"><%= @user.name %>さんのフォロワー</h3>
      <table class="table follower_lists">
        <% @users.each do |user| %>
          <tr>
            <td class="follower_user_image">
              <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: '/images/no_image.jpg' %>
            </td>
            <td class="follower_user_name">
              <%= link_to user_path(user.id), :style=> 'text-decoration: none;' do %>
                <p style="color: black;"><%= user.name %></p>
              <% end %>
            </td>
            <td class="follower_user_introduction">
              <%= user.introduction %>
            </td>
          </tr>
        <% end %>
      </table>
    <%= paginate @users %>
  </section>
</div>

app/views/users/timeline.html.erb
<!-- フォローしているユーザーの投稿 -->
<div class="container">
  <div class="row">
    <section class="col-sm-8">
      <% if @users.count == 0 %>
        <h2>まだ誰もフォローしていません。</h2>
      <% elsif @timeline.count == 0 %>
        <h2>まだ記事がありません。</h2>
      <% else %>
        <div class="jscroll">
          <% @timeline.each do |post| %>
            <div class="row timeline_contents page-header">
              <div class="col-xs-2 timeline_image">
                <%= attachment_image_tag post.user, :profile_image, format: 'jpeg', fallback: '/images/no_image.jpg' %>
              </div>
              <div class="col-xs-10">
                <%= link_to post_path(post.id), :style=> 'text-decoration: none;' do %>
                  <h4 style="color: black;"><%= post.title %></h4>
                <% end %>
                <%= post.body.truncate(100) %><br>
                <%= post.genre.genre_name %>
                <%= link_to user_path(post.user.id), :style=> 'text-decoration: none;' do %>
                  <div class="text-right" style="color: black;"><%= post.user.name %></div>
                <% end %>
                <p class="posted_date text-right"><%= post.created_at.strftime("%Y-%m-%d %H:%M") %></p>
              </div>
            </div>
          <% end %>
          <%= paginate @timeline %>
        </div>
      <% end %>
    </section>
    <aside class="col-sm-3 col-sm-offset-1 text-center timeline_sidebar">
      <%= render 'users/side', user: @user %>
    </aside>
  </div>
  <div class="toppage">
    <i class="fas fa-arrow-circle-up fa-3x"></i>
  </div>
</div>