config/routes.rb
Rails.application.routes.draw do

  root to: 'posts#top'
  get '/about' => 'static_pages#about'
  get 'posts/admin' => 'posts#admin'
  get 'top' => 'posts#top'

  devise_for :users
  resources :genres,         only: [:create, :index, :update, :destroy]
  resources :emotions,       only: [:create, :index, :update, :destroy]
  resources :contacts,       only: [:new, :create, :show, :index, :update, :destroy]
  resources :relationships,  only: [:create, :destroy]

  resources :users do
    member do
      get :following, :followers
      get :delete
      get :report
      get :timeline
    end
  end

  resources :posts,      only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :postimages
    resource :favorites, only: [:create, :destroy]
    resources :comments,  only: [:create, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :postimages, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :user
  belongs_to :genre
  belongs_to :emotion

  attachment :post_headerimage

  is_impressionable counter_cache: true


    validates :title, presence: true, length: { maximum: 100 }
    validates :body, presence: true, length: { maximum: 10000 }

#渡されたユーザidがfavoriteテーブル内に存在してるか
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search)#selfはPost
    if search
      where(['title LIKE ? OR body LIKE ?', "%#{search}%", "%#{search}%"])
    else# SQL記述 %は0字以上の任意文字列
      all
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :timeline]
  before_action :admin_user, only: [:admin]
  impressionist :actions=>[:show]#Pvカウント

  def new
    @post = Post.new
    # @post.postimages.build
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:notice] = "投稿しました。"
      redirect_to post_path(@post.id)
    else
      flash[:notice] = "失敗しました。必要項目を入力してください。"
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    impressionist(@post, nil, :unique => [:session_hash])
    @comment_counts = Comment.where(post_id: @post)
    @post_comments = Comment.page(params[:page]).where(post_id: @post).per(10)
    @comment = Comment.new
    @user = User.find_by(id: @post.user)
    @page_views = @post.impressions_count
# 人気ランキング
    post_favorite_count = Post.joins(:favorites).where(user_id: @user).group(:post_id).count
    post_favorited_ids = Hash[post_favorite_count.sort_by{ |_, v| -v }].keys
    @popular_posts = Post.where(id: post_favorited_ids).limit(5)
  end

  def index
    @posts = if params[:search]
      Post.page(params[:page]).per(21).where('title LIKE ? OR body LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%").reverse_order
    else
      Post.page(params[:page]).per(21).reverse_order
    end
  end

  def admin
    @posts = if params[:search]
      Post.page(params[:page]).per(20).where('title LIKE ? OR body LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%").reverse_order
    else
      Post.page(params[:page]).per(20).reverse_order
    end
  end

  def edit
    @post = Post.find(params[:id])
    unless @post.user.id == current_user.id
      redirect_to root_path
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "更新しました。"
      redirect_to post_path
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    if current_user.admin?
      flash[:notice] = "削除しました。"
      redirect_to posts_admin_path
    else
      user = User.find_by(id: post.user)
      flash[:notice] = "削除しました。"
      redirect_to edit_user_path(user)
    end
  end

  def top
    @posts_pv_count = Post.page(params[:page]).group(:impressions_count).order(impressions_count: :DESC).limit(5)
# ジャンル別人気欄
    genre_post_count = Post.all.group(:genre_id).count
    genre_post_ids = Hash[genre_post_count.sort_by{ |_, v| -v }].keys
    num = [0, 1, 2]
    @genre_popular_posts = num.map do |x|
      Post.where(genre_id: genre_post_ids[x]).order(impressions_count: 'DESC').limit(4)
    end
# ここまで
    popular_user_count = User.joins(:passive_relationships).group(:following_id).count
    popular_user_ids = Hash[popular_user_count.sort_by{ |_, v| -v }].keys
    @popular_users = User.where(id: popular_user_ids).limit(8)

    post_favorite_count = Post.joins(:favorites).group(:post_id).count
    post_favorited_ids = Hash[post_favorite_count.sort_by{ |_, v| -v }].keys
    @popular_posts = Post.where(id: post_favorited_ids).limit(10)
    @posts = Post.page(params[:page]).per(9).reverse_order
  end


  private

  def post_params
    params.require(:post).permit(:title, :body, :user_id, :genre_id, :emotion_id, :impressions_count, :post_headerimage)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comments.html.erb
<h4 class="text-center page-header"><%= comment_counts.count %>件コメント</h4>
<ol>
  <div class="row">
    <% post_comments.each do |comment| %>
      <li class="col-xs-10 col-xs-offset-1">
        <div class="row">
          <div class="col-xs-2 comment_image">
            <%= attachment_image_tag comment.user, :profile_image, format: 'jpeg', fallback: "/images/no_image.jpg" %>
          </div>
          <div class="col-xs-10">
            <%= link_to user_path(comment.user.id), :style=> 'text-decoration: none; color: black;' do %>
              <%= comment.user.name %>&nbsp;
            <% end %>
            <%= comment.created_at.strftime('%Y/%m/%d') %><br>
            <%= comment.comment %>
            <% if current_user && comment.user.id == current_user.id || current_user && current_user.admin == true %>
              <div class="text-right">
                <%= link_to "削除", post_comment_path(comment.post,comment.id), method: :delete, "data-confirm" => "削除しますか？", class: 'btn btn-default' %>
              </div>
            <% end %>
          </div>
        </div>
      </li>
    <% end %>
    <%= paginate post_comments %>
  </div>
</ol>
<!-- コメント送信フォーム -->
<% if user_signed_in? %>
  <%= form_for [post, comment] do |f| %>
    <%= f.text_area :comment, rows:'3', placeholder: "コメント", class: 'form-control' %>
    <%= f.submit "コメントを送信", class: 'btn btn-default' %>
  <% end %>
<% end %>

app/views/posts/_genres.html.erb
<!-- ジャンル別人気 -->
<div class="col-sm-4 genre">
  <h3 class="genre_top">
    <% genre_popular_posts[0].first(1).each do |post| %>
      <%= post.genre.genre_name %>
    <% end %>
  </h3>
  <% genre_popular_posts[0].each do |post| %>
    <div class="row genre_contents">
      <div class="col-xs-2 col-sm-4 genre_content_image">
        <%= attachment_image_tag post, :post_headerimage, format: 'jpeg', fallback: '/images/no_image.jpg' %>
      </div>
      <%= link_to post_path(post.id), :style=> 'text-decoration: none;' do %>
        <h4 class="genre_title" style="color: black;"><%= post.title.truncate(25) %></h4>
      <% end %>
      <%= link_to user_path(post.user.id), :style=> 'text-decoration: none;' do %>
        <p class="text-right genre_username" style="color: black;"><%= post.user.name %></p>
      <% end %>
    </div>
  <% end %>
</div>

<div class="col-sm-4 genre">
  <h3 class="genre_top">
    <% genre_popular_posts[1].first(1).each do |post| %>
      <%= post.genre.genre_name %>
    <% end %>
  </h3>
  <% genre_popular_posts[1].each do |post| %>
    <div class="row genre_contents">
      <div class="col-xs-2 col-sm-4 genre_content_image">
        <%= attachment_image_tag post, :post_headerimage, format: 'jpeg', fallback: '/images/no_image.jpg' %>
      </div>
      <%= link_to post_path(post.id), :style=> 'text-decoration: none;' do %>
        <h4 class="genre_title" style="color: black;"><%= post.title.truncate(25) %></h4>
      <% end %>
      <%= link_to user_path(post.user.id), :style=> 'text-decoration: none;' do %>
        <p class="text-right genre_username" style="color: black;"><%= post.user.name %></p>
      <% end %>
    </div>
  <% end %>
</div>

<div class="col-sm-4 genre">
  <h3 class="genre_top">
    <% genre_popular_posts[2].first(1).each do |post| %>
      <%= post.genre.genre_name %>
    <% end %>
  </h3>
  <% genre_popular_posts[2].each do |post| %>
    <div class="row genre_contents">
      <div class="col-xs-2 col-sm-4 genre_content_image">
        <%= attachment_image_tag post, :post_headerimage, format: 'jpeg', fallback: '/images/no_image.jpg' %>
      </div>
      <%= link_to post_path(post.id), :style=> 'text-decoration: none;' do %>
        <h4 class="genre_title" style="color: black;"><%= post.title.truncate(25) %></h4>
      <% end %>
      <%= link_to user_path(post.user.id), :style=> 'text-decoration: none;' do %>
        <p class="text-right genre_username" style="color: black;"><%= post.user.name %></p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/posts/_list.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th width="1%">ID</th>
      <th width="20%">タイトル</th>
      <th>本文</th>
      <th width="8%"></th>
      <th width="8%"></th>
      <th width="8%"></th>
    </tr>
  </thead>
  <tbody>
    <% posts.each do |post| %>
      <tr>
        <td><%= post.id %></td>
        <td><%= post.title.truncate(20) %></td>
        <td><%= post.body.truncate(50) %></td>
        <td><%= link_to "詳細", post_path(post.id) %></td>
        <td><%= link_to "編集", edit_post_path(post.id) %></td>
        <td><%= link_to "削除", post_path(post.id), method: :delete, "data-confirm" => "削除しますか？" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate posts %>

app/views/posts/admin.html.erb
<section class="container">
  <div class="row">
    <div class="col-xs-6 col-sm-4">
      <%= link_to posts_admin_path, :style=> 'text-decoration: none;' do %>
        <h1 class="admin_post_title" style="color: black;">記事管理</h1>
      <% end %>
    </div>
  <!-- 検索フォーム -->
    <div class="col-xs-6 col-sm-5">
      <%= form_tag(posts_admin_path, :method => 'get' ) do %>
        <div class="input-group admin_post_search">
          <%= text_field_tag :search, params[:search], class: 'form-control' %>
          <span class="input-group-btn">
            <%= submit_tag "検索", class: 'btn btn-default', :name => nil %>
          </span>
        </div>
      <% end %>
    </div>
    <% if @posts.count == 0 %>
    <% else %>
      <table class="table table-striped table-hover admin_posts">
        <thead>
          <tr class="admin_post">
            <th width="3%">ID</th>
            <th width="3%">ユーザーID</th>
            <th class="col-xs-1">ユーザー名</th>
            <th class="col-xs-1 admin_post_topimage">トップ画</th>
            <th class="col-xs-1">タイトル</th>
            <th class="col-xs-2">本文</th>
            <th width="6%"></th>
            <th width="6%"></th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
            <tr class="admin_post">
              <td><%= post.id %></td>
              <td><%= post.user.id %></td>
              <td>
                <%= link_to user_path(post.user.id), :style=> 'text-decoration: none;' do %>
                  <p style="color: black;"><%= post.user.name %></p>
                <% end %>
              </td>
              <td class="row admin_post_topimage">
                <div class="col-xs-10 admin_post_image">
                  <%= attachment_image_tag post, :post_headerimage, format: 'jpeg', fallback: '/images/no_image.jpg', class: 'post_headerimage' %>
                </div>
              </td>
              <td><%= post.title.truncate(50) %></td>
              <td><%= post.body.truncate(100) %></td>
              <td class="text-center"><%= link_to "詳細", post_path(post.id), class: 'btn btn-link' %></td>
              <td class="text-center"><%= link_to "削除", post_path(post.id), method: :delete, "data-confirm" => "削除しますか？", class: 'btn btn-link' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @posts %>
    <% end %>
  </div>
</section>

app/views/posts/edit.html.erb
<section class="container">
  <div class="row">
    <div class="col-xs-12">
      <h2>編集</h2>
    </div>
    <%= form_for @post do |f| %>
      <div class="col-xs-12 top_image">
        <%= f.label :post_headerimage, "トップ画" %>
        <%= f.attachment_field :post_headerimage %>
      </div>
      <div class="col-xs-3">
        <%= f.label :genre_id, "ジャンル" %>
        <%= f.collection_select :genre_id, Genre.all, :id, :genre_name, class: 'form-control input-sm' %>
      </div>
      <div class="col-xs-9">
        <%= f.label :emotion_id, "気分" %>
        <%= f.collection_select :emotion_id, Emotion.all, :id, :emotion_name, class: 'form-control input-sm' %>
      </div>
      <div class="col-xs-12">
        <%= f.label :title, "タイトル" %>
        <%= f.text_field :title, class: 'form-control' %>
        <%= f.label :body, "本文" %>
        <%= f.text_area :body, rows:'20', class: 'form-control input-lg' %><br>
      </div>
      <div class ="col-xs-6 col-xs-offset-3">
        <%= f.submit "編集", class: 'btn btn-default btn-block' %>
      </div>
    <% end %>
  </div>
</section>

app/views/posts/index.html.erb
<section class="container">
  <%= link_to posts_path, :style=> 'text-decoration: none;' do %>
    <h2 style="color: black;">記事一覧</h2>
  <% end %>
  <!-- 検索フォーム -->
  <% if @posts.count == 0 %>
  <% else %>
    <div class="row row-eq-height post_list">
      <% @posts.each do |post| %>
        <div class="col-xs-4 post_list_contents">
          <div class="row">
            <div class="col-xs-5 col-sm-6 post_list_image">
              <%= attachment_image_tag post, :post_headerimage, format: 'jpeg', fallback: '/images/no_image.jpg', class: 'post_headerimage' %>
            </div>
            <%= link_to post_path(post.id), :style=> 'text-decoration: none;' do %>
              <h4 class="post_list_title" style="color: black;"><%= post.title.truncate(20) %></h4>
            <% end %>
            <p class="post_list_genre"><%= post.genre.genre_name %></p>
            <div class="post_lists">
              <%= link_to user_path(post.user.id), :style=> 'text-decoration: none;' do %>
                <div class="text-right post_list_username" style="color: black;"><%= post.user.name %></div>
              <% end %>
              <p class="post_list_date text-right"><%= post.created_at.strftime("%Y-%m-%d") %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <%= paginate @posts %>
  <% end %>
</section>

app/views/posts/new.html.erb
<section class="container">
  <div class="row">
    <div class="col-xs-12">
      <h2>新規投稿</h2>
    </div>
    <%= form_for @post do |f| %>
      <div class="col-xs-12 top_image">
        <%= f.label :post_headerimage, "トップ画" %>
        <%= f.attachment_field :post_headerimage %>
      </div>
      <div class="col-sm-5 col-md-4 col-lg-3">
        <%= f.label :genre_id, "ジャンル" %>
        <%= f.collection_select :genre_id, Genre.all, :id, :genre_name, class: 'form-control input-sm' %>
      </div>
      <div class="col-sm-7 col-md-8 col-lg-9">
        <%= f.label :emotion_id, "気分" %>
        <%= f.collection_select :emotion_id, Emotion.all, :id, :emotion_name, class: 'form-control input-sm' %>
      </div>
      <div class="col-xs-12">
        <%= f.label :title, "タイトル" %>
        <%= f.text_field :title, class: 'form-control' %>
        <%= f.label :body, "本文" %>
        <%= f.text_area :body, rows:'20', class: 'form-control input-lg' %><br>
      </div>
      <div class ="col-xs-6 col-xs-offset-3">
        <%= f.submit "投稿", class: 'btn btn-default btn-block' %>
      </div>
    <% end %>
  </div>
</section>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <section class="col-xs-9 post_show">
      <h2 class="post_title"><%= @post.title %></h2>
      <p><%= @post.genre.genre_name %></p>
      <p class="posted_date">投稿日:<%= @post.created_at.strftime("%Y-%m-%d %H:%M") %></p>
      <div class="row">
        <div class="col-xs-6 col-xs-offset-3 post_image">
          <%= attachment_image_tag @post, :post_headerimage, format: 'jpeg', fallback: '/images/no_image.jpg', class: 'post_headerimage' %>
        </div>
      </div>
      <div>
        <%= markdown(@post.body).html_safe %>
      </div>
      <p class="text-right"><%= @post.emotion.emotion_name %></p>
      <br>
      <p>閲覧数:<%= number_with_delimiter(@page_views) %>回</p>
    <!-- いいね欄 favorited_by?はmodelに定義したもの-->
      <% if user_signed_in? %>
        <% if @post.favorited_by?(current_user) %>
          <%= link_to post_favorites_path(@post), :style=> 'text-decoration: none;', method: :delete do %>
            <i class="fa fa-heart" style="color: red;"></i>
          <% end %>
          <%= @post.favorites.count %>
        <% else %>
          <%= link_to post_favorites_path(@post), :style=> 'text-decoration: none;', method: :post do %>
            <i class="far fa-heart"></i>
          <% end %>
          <%= @post.favorites.count %>
        <% end %>
      <% else %>
        <i class="far fa-heart"></i>
        <%= @post.favorites.count %>
      <% end %>
    <!-- コメント欄 -->
      <%= render 'posts/comments', post: @post, comment_counts: @comment_counts,
                                   post_comments: @post_comments, comment: @comment %>
    </section>
    <!-- サイドバー -->
    <aside class="col-xs-3 text-center post_sidebar">
      <h4 class="page-header popular_headertitle">人気記事ランキング</h4>
      <% @popular_posts.each do |post| %>
        <div class="row popular_post">
          <div class="col-xs-5 user_popular_image">
            <%= attachment_image_tag post, :post_headerimage, format: 'jpeg', fallback: '/images/no_image.jpg', class: 'popular_headerimage' %>
          </div>
          <%= link_to post_path(post.id), :style=> 'text-decoration: none;' do %>
            <p class="text-left user_popularpost_title" style="color: black;"><%= post.title.truncate(20) %></p>
            <p class="text-left user_popularpost_genre" style="color: black;"><%= post.genre.genre_name %></p>
          <% end %>
        </div>
      <% end %>
      <div class="post_sidebar_bottom">
        <%= render 'users/side', user: @user %>
      </div>
    </aside>
  </div>
</div>

app/views/posts/top.html.erb
<div class="container-fluid top">
  <div class="top_contents">
    <% @posts_pv_count.each do |post| %>
      <div class="item">
        <%= attachment_image_tag post, :post_headerimage, format: 'jpeg', fallback: '/images/no_image.jpg' %>
        <%= link_to post_path(post.id), :style=> 'text-decoration: none;' do %>
          <h4 style="color: black;"><%= post.title.truncate(26) %></h4>
        <% end %>
        <p><%= post.genre.genre_name %></p>
        <%= link_to user_path(post.user.id), :style=> 'text-decoration: none;' do %>
          <p class="text-right top_username" style="color: black;"><%= post.user.name %></p>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<!-- ジャンル -->
<div class="container">
  <div class="row">
    <section class="genres">
      <h3 class="col-xs-12 page-header">ジャンル</h3>
      <%= render 'posts/genres', genre_popular_posts: @genre_popular_posts %>
    </section>
  </div>
<!-- おすすめ記事 -->
  <div class="row">
    <section class="col-xs-7 popular_posts">
      <h3 class="page-header">おすすめ記事</h3>
      <div class="row row-eq-height">
        <% @popular_posts.each do |post| %>
          <div class="col-xs-6 popular_contents">
            <div class="row">
              <div class="col-xs-5 col-sm-6 popular_content_image">
                <%= attachment_image_tag post, :post_headerimage, format: 'jpeg', fallback: '/images/no_image.jpg', class: 'post_headerimage' %>
              </div>
              <%= link_to post_path(post.id), :style=> 'text-decoration: none;' do %>
                <h4 class="popular_content_title" style="color: black;"><%= post.title.truncate(20) %></h4>
              <% end %>
              <p class="popular_genre_name"><%= post.genre.genre_name %></p>
              <%= link_to user_path(post.user.id), :style=> 'text-decoration: none;' do %>
                <p class="text-right popular_post_username" style="color: black;"><%= post.user.name %></p>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </section>
  <!-- おすすめユーザー -->
    <section class="col-xs-4 col-sm-offset-1 popular_users">
      <h3 class="page-header">おすすめのユーザー</h3>
      <% @popular_users.each do |user| %>
        <div class="row user_contents">
          <div class="col-xs-4 col-sm-5 user_content_image">
            <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: '/images/no_image.jpg', class: 'profile_image' %>
          </div>
          <%= link_to user_path(user.id), :style=> 'text-decoration: none;' do %>
            <h4 class="popular_username" style="color: black;"><%= user.name %></h4>
            <% if user.introduction? %>
              <p class="popular_user_introduction" style="color: black;"><%= user.introduction.truncate(30) %></p>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </section>
  </div>
<!-- 新着記事 -->
  <div class="row">
    <section class="new_posts">
      <h3 class="page-header">新着記事</h3>
      <div class="jscroll">
        <% @posts.each do |post| %>
          <div class="col-xs-4 new_contents">
            <div class="row">
              <div class="col-xs-5 col-sm-6 new_content_image">
                <%= attachment_image_tag post, :post_headerimage, format: 'jpeg', fallback: '/images/no_image.jpg', class: 'post_headerimage' %>
              </div>
              <%= link_to post_path(post.id), :style=> 'text-decoration: none;' do %>
                <h4 class="new_post_title" style="color: black;"><%= post.title.truncate(20) %></h4>
              <% end %>
              <p class="new_post_genre"><%= post.genre.genre_name %></p>
              <%= link_to user_path(post.user.id), :style=> 'text-decoration: none;' do %>
                <p class="text-right new_post_username" style="color: black;"><%= post.user.name %></p>
              <% end %>
            </div>
          </div>
        <% end %>
        <%= paginate @posts %>
      </div>
    </section>
  </div>
  <div class="toppage">
    <i class="fas fa-arrow-circle-up fa-3x"></i>
  </div>
</div>