config/routes.rb
Rails.application.routes.draw do

  root to: 'posts#top'
  get '/about' => 'static_pages#about'
  get 'posts/admin' => 'posts#admin'
  get 'top' => 'posts#top'

  devise_for :users
  resources :genres,         only: [:create, :index, :update, :destroy]
  resources :emotions,       only: [:create, :index, :update, :destroy]
  resources :contacts,       only: [:new, :create, :show, :index, :update, :destroy]
  resources :relationships,  only: [:create, :destroy]

  resources :users do
    member do
      get :following, :followers
      get :delete
      get :report
      get :timeline
    end
  end

  resources :posts,      only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :postimages
    resource :favorites, only: [:create, :destroy]
    resources :comments,  only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user, optional: true #nilを許可
	belongs_to :post

	validates :comment, presence: true, length: { maximum: 150 }
end

app/models/contact.rb
class Contact < ApplicationRecord
	belongs_to :user

	validates :title, length: { minium:4, maximum: 50 }
	validates :contact_content, length: { minium:10, maximum: 1000 }
end

app/models/emotion.rb
class Emotion < ApplicationRecord
	has_many :posts

	validates :emotion_name, presence: true,
							 length: { maximum: 10 },
							 uniqueness: true #値がユニークか検証する
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts

  validates :genre_name, presence: true,
            length: { maximum: 12 },
            uniqueness: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :postimages, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :user
  belongs_to :genre
  belongs_to :emotion

  attachment :post_headerimage

  is_impressionable counter_cache: true


    validates :title, presence: true, length: { maximum: 100 }
    validates :body, presence: true, length: { maximum: 10000 }

#渡されたユーザidがfavoriteテーブル内に存在してるか
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search)#selfはPost
    if search
      where(['title LIKE ? OR body LIKE ?', "%#{search}%", "%#{search}%"])
    else# SQL記述 %は0字以上の任意文字列
      all
    end
  end
end

app/models/postimage.rb
class Postimage < ApplicationRecord
	belongs_to :post
	attachment :image
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	# フォローする側
	belongs_to :follower, class_name: "User"
	#される側
	belongs_to :following, class_name: "User"

	validates :follower_id, presence: true
	validates :following_id, presence: true

#belongs_to 変更したい親モデル名, class_name: "元々の親モデル名"。
#これでFollowモデル、Followerモデルを擬似的に作る。
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
# フォローする側(active_relationships)擬似的に作成。foreign_keyでされる側id指定している
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
#フォローしているユーザーを取り出す
  has_many :following, through: :active_relationships
# フォローされてるユーザーを取り出せる(user.followers)
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :followers, through: :passive_relationships

  attachment :profile_image
  attachment :profile_headerimage

  validates :name, presence: true, length: { minimum: 2, maximum: 15 }
  validates :introduction, length: { maximum: 150 }
  validates :email, presence: true, length: { maximum: 80 }


# フォロー関連
  def follow(other_user)
    active_relationships.create(following_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(following_id: other_user.id).destroy
  end
	# フォローしているかどうか(t or f)
  def following?(other_user)
    following.include?(other_user)
  end

# 検索関連
  def self.search(search)#selfはUser
    if search
      where(['name LIKE ?', "%#{search}%"])#検索内とnameの部分一致を表示
    else# SQL記述 %は0字以上の任意文字列
      all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	require "redcarpet"
	require "coderay"


	class HTMLwithCoderay < Redcarpet::Render::HTML
		def block_code(code, language)
			language = language.split(':')[0]

			case language.to_s
            when 'rb'
                lang = 'ruby'
            when 'yml'
                lang = 'yaml'
            when 'css'
                lang = 'css'
            when 'html'
                lang = 'html'
            when ''
                lang = 'md'
            else
                lang = language
            end

            CodeRay.scan(code, lang).div
        end
	end

	def markdown(text)
        html_render = HTMLwithCoderay.new(filter_html: true)#ユーザー入力HTMLを出力をしない
        options = {
            autolink: true,
            space_after_headers: true,
            no_intra_emphasis: true,#単語中の強調を認識しない
            fenced_code_blocks: true,#```に囲まれた部分をコードとしてできる
            tables: true,
            hard_wrap: true,#行末にスペース2ついれなくても改行できるように
            xhtml: true,#xhtml のタグを出力する
            lax_html_blocks: true,#HTMLブロックの上下に改行不要
            strikethrough: true#取り消し線(~)を解析する
        }
        markdown = Redcarpet::Markdown.new(html_render, options)#オプション内容渡している
        markdown.render(text)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/emotions_helper.rb
module EmotionsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/postimages_helper.rb
module PostimagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-2 text-center">
        <%= link_to root_path, :style=> 'text-decoration: none;' do %>
            <h1 class="header_title" style="color: black;">Arche</h1>
        <% end %>
      </div>
    <!-- 検索フォーム -->
      <div class="col-xs-3 header_search">
        <%= form_tag(posts_path, :method => 'get') do %>
          <div class="input-group">
            <%= text_field_tag :search, params[:search], class: 'form-control' %>
            <span class="input-group-btn">
              <%= submit_tag "検索", :name => nil, class: 'btn btn-default' %>
            </span>
          </div>
        <% end %>
      </div>
    <!-- ヘッダーnavバー -->
      <% if current_user && current_user.admin == true %>
        <div class="col-xs-7 header_nav">
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" style="color: black;">管理 <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "ユーザー管理", users_path %></li>
                  <li><%= link_to "問い合わせ管理", contacts_path %></li>
                  <li><%= link_to "記事管理", posts_admin_path %></li>
                  <li><%= link_to "ジャンル管理", genres_path %></li>
                  <li><%= link_to "気分管理", emotions_path %></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" style="color: black;">ユーザー関連 <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "新規投稿", new_post_path %></li>
                  <li><%= link_to "ユーザー記事管理", edit_user_path(current_user) %></li>
                  <li><%= link_to "レポート", report_user_path(current_user) %></li>
                  <li><%= link_to "問い合わせ", new_contact_path %></li>
                </ul>
              </li>
              <li>
                <%= link_to "タイムライン", timeline_user_path(current_user), :style=>'color: black;' %>
              </li>
              <li>
                <%= link_to "このサイトについて", about_path, :style=>'color: black;' %>
              </li>
              <li>
                <%= link_to current_user.name, user_path(current_user), :style=>'color: black; text-decoration: none;' %>
              </li>
              <li>
                <%= link_to "ログアウト", destroy_user_session_path, :style=>'color: black; text-decoration: none;', method: :delete %>
              </li>
            </ul>
          </div>
        </div>
      <% elsif current_user && current_user.admin == false %>
        <div class="col-xs-7 header_nav">
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" style="color: black;">ユーザー関連 <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "新規投稿", new_post_path %></li>
                  <li><%= link_to "ユーザー記事管理", edit_user_path(current_user) %></li>
                  <li><%= link_to "レポート", report_user_path(current_user) %></li>
                  <li><%= link_to "問い合わせ", new_contact_path %></li>
                </ul>
              </li>
              <li>
                <%= link_to "タイムライン", timeline_user_path(current_user), :style=>'color: black;' %>
              </li>
              <li>
                <%= link_to "このサイトについて", about_path, :style=>'color: black;' %>
              </li>
              <li>
                <%= link_to current_user.name, user_path(current_user), :style=>'color: black; text-decoration: none;' %>
              </li>
              <li>
                <%= link_to "ログアウト", destroy_user_session_path, :style=>'color: black; text-decoration: none;', method: :delete %>
              </li>
            </ul>
          </div>
        </div>
      <% else %>
        <div class="col-xs-4 col-xs-offset-3 header_nav">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to "このサイトについて", about_path, :style=>'color: black;' %>
            </li>
            <li>
              <%= link_to "ゲスト", new_user_session_path, :style=>'color: black; text-decoration: none;' %>
            </li>
            <li>
              <%= link_to "新規登録", new_user_registration_path, :style=>'color: black; text-decoration: none;'%>
            </li>
            <li>
              <%= link_to "ログイン", new_user_session_path, :style=>'color: black; text-decoration: none;' %>
            </li>
          </ul>
        </div>
      <% end %>
    <!-- ハンバーガーメニュー -->
      <div id="hm_icon">
        <a class="hm_menu" href="#">
          <span></span>
          <span></span>
          <span></span>
        </a>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arche</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- bootstrapレスポンシブ -->
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" >
  <!-- 無限スクロール jscroll -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jscroll/2.4.1/jquery.jscroll.min.js"></script>
  <!-- スライドslick -->
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <div class="wrap">
      <% if flash[:notice] %>
        <div class="flash alert alert-info alertfadeout">
          <%= flash[:notice] %>
          <button type="button" class="close" data-dismiss="alert" aria-label="閉じる"><span aria-hidden="true">×</span></button>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <footer>
      <p>©︎2019 Arche</p>
    </footer>
  </body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arche</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- bootstrapレスポンシブ -->
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" >
  <!-- 無限スクロール jscroll -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jscroll/2.4.1/jquery.jscroll.min.js"></script>
  <!-- スライドslick -->
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
  </head>

  <body>
    <header>
      <div class="headerimage">
        <%= attachment_image_tag @user, :profile_headerimage, format: 'jpeg', width: '150', height: '200', class: 'profile_headerimage' %>
      </div>
      <%=  render 'layouts/header' %>
    </header>
    <div class="wrap">
      <% if flash[:notice] %>
        <div class="flash alert alert-info alertfadeout">
          <%= flash[:notice] %>
          <button type="button" class="close" data-dismiss="alert" aria-label="閉じる"><span aria-hidden="true">×</span></button>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <footer>
      <p>©︎2019 Arche</p>
    </footer>
  </body>
</html>